### ISSUE TITLE
包含图片规则无效

### ISSUE THREAD

**Issue by spysir** [sekai-soft/rss-lambda#2]
原RSS
https://rsshub.app/telegram/channel/landiansub
转换后RSS
https://rss-lambda.ktachibana.party/rss?url=https%3A%2F%2Frsshub.app%2Ftelegram%2Fchannel%2Flandiansub&op=filter_desc_cont_img
用Miniflux阅读器查看还是有无图片的文章

**Comment by KTachibanaM** [comment]
Should have been fixed in https://github.com/k-t-corp/rss-lambda/commit/aa9e9e425a0b4cf2e8f3296d6ebd3a66e01275e5
